### ISSUE TITLE
[sonarqube]: multiple replicas

### ISSUE THREAD

**Issue by vittoriocanilli** [Oteemo/charts#152]
I am trying to set `replicaCount: 2` in the values.yaml file, but as soon as the replica set is ready and I try to log on SonarQube, it simply return the log-in screen again.

Is there any additional option to set to have multiple replicas?

I have tried the following:
`jvmOpts: "-Djgroups.dns.query=sonarqube-sonarqube.<NAMESPACE>:9000 -Djava.net.preferIPv4Stack=true"`
where `<NAMESPACE>` is the namespace where SonarQube is deployed, but unfortunately it did not help.

Does actually SonarQube Community support multiple replicas? Thanks in advance.

**Comment by ricardojdsilva87** [comment]
Hello @vittoriocanilli , 
We had that issue also, and was able to surpass it by changing the ingress controller to nginx. We found out that we needed to have the cookies options also with affinity for the login to be persistent.

**Comment by vittoriocanilli** [comment]
Hello @ricardojdsilva87 ,
thanks for your suggestion: I have indeed added these Nginx annotations to my ingress:
```
nginx.ingress.kubernetes.io/affinity: cookie
nginx.ingress.kubernetes.io/affinity-mode: balanced
```
and I confirm that it works, but that makes all requests going to the same pod and the session is lost in case the pod is deleted: the pods run in this configuration as stand-alone, and not as in a cluster.

**Comment by ricardojdsilva87** [comment]
In our case we don't mind that the session is lost after the pod is recreated, the user just needs to relogin. For nginx I'm not sure if there is any option to store the session across multiple pods. The cookie must need to have probably some kind of different options needed to pass trough the configuration others than the default ones to have the behaviour you've mentioned. Not sure which ones.
The behaviour we intended to have was to redeploy at any time sonarqube and the user won't notice. because it's a Rolling-update deployment. The only issue the user might find is having to relogin but as we have the database centralized the sonarqube pod is used only as a frontend, the changes would be saved anyway after relogin.

**Comment by peppe77** [comment]
Hi,

is it possible to have Sonarqube configured as a cluster (HA mode) ? thanks

**Comment by peppe77** [comment]
btw: i set replicaCount: 2 and was not able to get 2nd up...anything else I might be missing? @ricardojdsilva87 @vittoriocanilli 

`2020.09.15 02:33:04 WARN  es[][o.e.b.ElasticsearchUncaughtExceptionHandler] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/opt/sonarqube/data/es6]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.4.jar:6.8.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.4.jar:6.8.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.4.jar:6.8.4]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/opt/sonarqube/data/es6]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:300) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.4.jar:6.8.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.4.jar:6.8.4]`

**Comment by ricardojdsilva87** [comment]
Hello @vittoriocanilli , we have the pods running in different nodes 1 per node not sure if that we didn't encounter that issue. Running in 3 AZs. We also are using an external database common to all 3 pods. For all of the pods we have also not set a PV, we are running them with ephemeral storage, we saw that it was not needed because all the settings are saved in the RDS and we can set most of the things in the helm chart, plugins included.

**Comment by stevefan1999-personal** [comment]
Yes. It probably requires sticky session. This is why we need to relogin because there's no session on that random server.

**Comment by vittoriocanilli** [comment]
Hello and sorry for the late reply!

@ricardojdsilva87 @stevefan1999-personal I confirm that the solution with the sticky sessions works fine for me as I have as well a common database behind the two pods.

@peppe77 did you manage to solve your problem meanwhile? did you have it even with 1 replica? As far as I remember I had problems with ElasticSearch at the beginning even with one replica, so I have disabled it with these values:
```
elasticsearch:
  configureNode: false
  bootstrapChecks: false
initSysctl:
  enabled: false
  securityContext:
    privileged: false
```

I did not research further how to setup SonarQube as cluster: not sure if somebody else in this thread had success meanwhile.
I hope it helps.

**Comment by lpmatos** [comment]
Same problem here ... When I set the replicaCount to `2`, the second pod crash.

**Comment by ricardojdsilva87** [comment]
Not sure if this is related, but we have the replicas in separated nodes since we have our setup in HA.
Also have the following affinity setting to prevent 2 pods to be scheduled to the same node:
```
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - sonarqube
      topologyKey: "kubernetes.io/hostname"
```

Not sure if this is the different for your setup

**Comment by peppe77** [comment]
@vittoriocanilli I was able to get it up and running with 1 replica though have not yet found a way to get multiple replicas working :( @ricardojdsilva87 : how did you handle pv/pvcs or you do not have persistence turned on? we have 1 replica bound to pvc/pv though if we add 2 more replicas (let's say one per region) then persistence becomes a challenge. any thoughts?

**Comment by ricardojdsilva87** [comment]
Hello @peppe77
To have multiple replicas I have disabled the persistence option. The pods spin up with ephemeral storage, you can configure basically every option of sonarqube via the helm chart.
To have the option to remove the persistent storage you'll need to have an external database in place, we are using an postgresql RDS with the multi AZ option. But you can have the same RDS with only 1 single AZ, also you can run multiple pods in the same node since they don't need to share the same information on a PV, all the projects should be saved on the RDS itself.
The reason for us to have the affinity option for the pods is to enable HA, having multiple pods running in different nodes in different AZs.
Hope this explanation helps you

**Comment by fl-max** [comment]
@ricardojdsilva87 [solution](https://github.com/Oteemo/charts/issues/152#issuecomment-772584946) worked for me. IMO this should be part of the Chart.

**Comment by ArjonBu** [comment]
@fl-max Same. but the issue seems to be when the app will save the data to the database. First it says that the data failed to persist to the DB and the background task is canceled. If I check in a few minutes, the data is persisted (maybe by another replica).

**Comment by vittoriocanilli** [comment]
> @vittoriocanilli I was able to get it up and running with 1 replica though have not yet found a way to get multiple replicas working :( 

@peppe77 sorry for the late reply; I can have 2 replicas running on my AKS cluster and I use an Azure-hosted PostgreSQL (Basic, 2 vCores, 20 GB storage) as database; the persistent storage is disable in the Helm chart. I hope it helps (maybe you have already solved the issue meanwhile).


> @vittoriocanilli I am seeing issues where the result is not saved to the DB sometimes and this seems to be a problem when you use the same db for all replicas. Have you experienced this?

@ArjonBu I use a database and this morning I have noticed your same error in my logs:

```
2022.02.07 08:07:51 INFO ce[XXXXX][o.s.c.t.s.ComputationStepExecutor] Trigger refresh of Portfolios and Applications | status=SUCCESS | time=0ms
2022.02.07 08:07:51 INFO ce[XXXXX][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Webhooks | globalWebhooks=0 | projectWebhooks=0 | status=SUCCESS | time=24ms
2022.02.07 08:07:52 ERROR ce[XXXXX][o.s.c.t.CeWorkerImpl] Failed to finalize task with uuid 'XXXXX' and persist its state to db
java.lang.IllegalStateException: Task does not exist anymore: CeTask{type=REPORT, uuid=XXXXX, component=Component{uuid='YYYYY', key='com.company.project:project-name', name='project-name'}, mainComponent=Component{uuid='YYYYY', key='com.company.project:project-name', name='project-name'}, submitter=User{uuid='project-name', login='project-name'}}
at org.sonar.ce.queue.InternalCeQueueImpl.lambda$remove$0(InternalCeQueueImpl.java:123)
at java.base/java.util.Optional.orElseThrow(Optional.java:408)
at org.sonar.ce.queue.InternalCeQueueImpl.remove(InternalCeQueueImpl.java:123)
at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.finalizeTask(CeWorkerImpl.java:245)
at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.afterExecute(CeWorkerImpl.java:239)
at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.close(CeWorkerImpl.java:199)
at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:161)
at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
2022.02.07 08:07:52 INFO ce[XXXXX][o.s.c.t.CeWorkerImpl] Executed task | project=com.company.project:project-name | type=REPORT | id=XXXXX | submitter=project-name | status=SUCCESS | time=112231ms
```

Anyway I can find the task with that ID as background task of the project shown in the SonarQube GUI with **CANCELED** as status. My colleagues using SonarQube have never complained of missing data so far.
