### ISSUE TITLE
[sonarqube] when helm upgrade, there's a problem

### ISSUE THREAD

**Issue by Hokwang** [Oteemo/charts#236]
Hi,

please look at below command and output.

I installed sonarqube and it works normally.
and I changed some vaules and `helm upgrade` it has problem.

```
$ k get pod -n sonarqube-stage
NAME                                                   READY   STATUS    RESTARTS   AGE
sonarqube-stage-postgresql-postgresql-primary-0        2/2     Running   0          5h37m
sonarqube-stage-postgresql-read-0                      1/1     Running   0          5h37m
sonarqube-stage-postgresql-read-1                      1/1     Running   0          5h36m
sonarqube-stage-sonarqube-sonarqube-6ff96fcc59-fkdlm   1/1     Running   0          7m10s

$ helm upgrade -n sonarqube-stage sonarqube-stage-sonarqube -f sonarqube-stage-sonarqube-values.yaml oteemocharts/sonarqube
Release "sonarqube-stage-sonarqube" has been upgraded. Happy Helming!
NAME: sonarqube-stage-sonarqube
LAST DEPLOYED: Mon Jan  4 23:35:22 2021
NAMESPACE: sonarqube-stage
STATUS: deployed
REVISION: 3
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  http://my.company.net

$ k get pod -n sonarqube-stage
NAME                                                   READY   STATUS             RESTARTS   AGE
sonarqube-stage-postgresql-postgresql-primary-0        2/2     Running            0          5h17m
sonarqube-stage-postgresql-read-0                      1/1     Running            0          5h17m
sonarqube-stage-postgresql-read-1                      1/1     Running            0          5h16m
sonarqube-stage-sonarqube-sonarqube-6ff96fcc59-fkdlm    1/1     Running            0          78m
sonarqube-stage-sonarqube-sonarqube-584fddb84d-v6wgp   0/1     CrashLoopBackOff   7          12m

$ k logs -n sonarqube-stage sonarqube-stage-sonarqube-sonarqube-584fddb84d-v6wgp
2021.01.04 14:35:52 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2021.01.04 14:35:52 ERROR app[][o.s.application.App] Startup failure
java.nio.file.FileSystemException: /opt/sonarqube/temp/ce-exploded-plugins/python/.nfs0000000010c823100000004d: Device or resource busy
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1141)
	at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:192)
	at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:186)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
	at org.sonar.process.FileUtils2.deleteDirectoryImpl(FileUtils2.java:148)
	at org.sonar.process.FileUtils2.deleteDirectory(FileUtils2.java:121)
	at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:117)
	at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:101)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
	at org.sonar.application.AppFileSystem.createOrCleanTempDirectory(AppFileSystem.java:96)
	at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:62)
	at org.sonar.application.App.start(App.java:62)
	at org.sonar.application.App.main(App.java:97)
```

I thinks the cause is that two pod use same pvc.

**Comment by jkirkham-ratehub** [comment]
I've run into this issue too.
Due to the number of nodes (1) allowed by the community license you can only have one pod running at a time.  You will need to add this to your Helm values file:
```yaml
        deploymentStrategy:
           type: Recreate
```
This will force the old pod to fully terminate before starting the new one.

**Comment by Hokwang** [comment]
@jkirkham-ratehub thanks!
