### ISSUE TITLE
nexus-proxy container error

### ISSUE THREAD

**Issue by jemishdave** [Oteemo/charts#51]
Getting the below error when nexus-proxy starts.
Tried setting env var for the nexus-proxy container as per the below reference link but same error
```
nexusProxy:
  enabled: true
  env:
    disableFileCPResolving: true
```

Reference: https://github.com/eclipse-vertx/vert.x/issues/1931
```Exception` in thread "main" java.lang.IllegalStateException: Failed to create cache dir
        at io.vertx.core.impl.FileResolver.setupCacheDir(FileResolver.java:299)
        at io.vertx.core.impl.FileResolver.<init>(FileResolver.java:92)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:176)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:143)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:139)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:34)
        at io.vertx.core.Vertx.vertx(Vertx.java:80)
        at com.travelaudience.nexus.proxy.Main.main(Main.java:17)```

**Comment by namloc2001** [comment]
You could try setting `JAVA_TOOL_OPTIONS "-Dvertx.cacheDirBase=<location_you_can_write_to"`
