### ISSUE TITLE
[Sonarqube statefulset] Provide option to switch between statefulset vs deployment for sonarqube.

### ISSUE THREAD

**Issue by rverma-jm** [Oteemo/charts#72]
Hi!

First of all: Thanks for taking on the sonarqube chart!
Wondering what's your view point in use sonarqube in statefulset. This is mostly required to replace the extensions/libs installed PVC.

**Comment by rjkernick** [comment]
I think statefulsets make sense for it. Not something I thought of a couple a years ago when the chart was made. You could even make it a switch like what is done in the sonatype-nexus chart in this repository.

**Comment by p0bailey** [comment]
Would a stateful set mitigate the issue below? 

https://community.sonarsource.com/t/sonarqube-failing-on-kubernetes-eks-with-persisten-storage-and-rolling-update-deploymentstrategy/24294

**Comment by rverma-jm** [comment]
Rolling update will be very tricky in stateful applications, specially for those which are not configured in ha by default. I bet you would be running sonarqube with replica size 1. If you are using replicasize >1, it's certainly possible to do rolling update on kubernetes 1.17+.

If you are on single instance you have to use a storage disk which support readwritemany option. But it can literally corrupt on breaking change. 

For postgres https://kubernetes.io/blog/2017/02/postgresql-clusters-kubernetes-statefulsets/

**Comment by p0bailey** [comment]
Hi @rverma-jm  
Thanks for your heads up. Problem that I'm trying to solve is to have SonarQube on Kuberbetes performing a seamless rolling update with a persistent storage enabled. Yes, I agree that statefull applications are tricky. 

Please forgive me but I din't catch you on:

_If you are on single instance you have to use a storage disk which support readwritemany option. But it can literally corrupt on breaking change._

Thanks a lot.

Phillip

**Comment by rverma-jm** [comment]
This is from
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes.
EFS is a readwritemany storage option while ens is readwriteonce.
The difference is how many nodes can share this.

The downside is if 2 concurrent instances of sonarqube flush something at
same time to disk, we don't know which one will be persisted. In some cases
this kind of thing corrupts the whole data
cause of 1 bad sector. This is something which could be tried though.

**Comment by p0bailey** [comment]
@rverma-jm 

Hi rvervma,

Just tried with EFS with readwritemany and still getting.

2020.05.09 10:50:30 WARN  es[][o.e.b.ElasticsearchUncaughtExceptionHandler] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/opt/sonarqube/data/es6]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.4.jar:6.8.4]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.4.jar:6.8.4]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.4.jar:6.8.4]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/opt/sonarqube/data/es6]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:300) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.4.jar:6.8.4]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.4.jar:6.8.4]
        ... 6 more
2020.05.09 10:50:30 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 1
2020.05.09 10:50:30 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2020.05.09 10:50:30 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by rverma-jm** [comment]
It seems that its be design and this seems either needed to be implemented by community or you have to opt in for data center edition of sonarqube. That supported the HA requirement https://docs.sonarqube.org/latest/setup/install-cluster/.

However what I found that its entirely possible to scale sonarqube deployment to 2. If somehow you can configure `sonar.search.properties` with the right discovery parameters as here https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-hosts-providers.html, then es will take care of data replication.

Its unfortunate that sonarqube doesn't support external es in any edition.

**Comment by p0bailey** [comment]
@rverma-jm 

Hi Rverma,

spot on. I had reach the same conclusions few days ago and I wanted a kind of second opinion on the subject. In the other hand I can do rolling updates using no persistence. What is the downside of not having SonarQube running with no persistence enabled?

Best regards,

Phillip

**Comment by rverma-jm** [comment]
you will keep on losing your previous scan's data on every deployment.

**Comment by p0bailey** [comment]
@rverma-jm 

Hi Rverma,

scans and results are stored into the SonarDB i.e.  RDS postgresq. In the case of a volatile setup the challenge is that everytime a pod gets recheduled has to re-download the plugins. But, about elasticsearch I don't quite get the risks of not having it on a persisted storage.

Kind regsards,

Phillip
